### Hire List
GET http://localhost:8000/api/hire/
Accept: application/json

### Hire Job List
GET http://localhost:8000/api/hire/job
Accept: application/json


### Hire register
POST http://localhost:8000/api/hire/register
Content-Type: application/json

{
  "companyName": "Ali",
  "email": "asas1121421rtt@kar.com",
  "password": "12345",
  "taxNumber": "123457685",
  "taxOffice": "office",
  "phoneNumber": "564645646",
  "address": "adress",
  "ascac": "ascac"
}

###
POST http://localhost:8000/api/hire/login
Content-Type: application/json

{
  "email": "test@tes.com",
  "password": "54564564"
}

### Hire job create
POST http://localhost:8000/api/hire/job/create
Content-Type: application/json

{
  "description": "test description",
  "gender": "male",
  "startDate": "2022-06-20T12:49:23.471Z",
  "endDate": "2022-06-20T12:49:23.471Z",
  "companyId": 4,
  "categoryId": 1
}

### Hire job update
PUT http://localhost:8000/api/hire/job/update/4
Content-Type: application/json

{
  "description": "Açıklama"
}

###
DELETE http://localhost:8000/api/hire/job/delete/3
Content-Type: application/json

{}
