"use strict";
// const cities = {
//   "1": "ADANA",
//   "2": "ADIYAMAN",
//   "3": "AFYONKARAHİSAR",
//   "4": "AĞRI",
//   "5": "AMASYA",
//   "6": "ANKARA",
//   "7": "ANTALYA",
//   "8": "ARTVİN",
//   "9": "AYDIN",
//   "10": "BALIKESİR",
//   "11": "BİLECİK",
//   "12": "BİNGÖL",
//   "13": "BİTLİS",
//   "14": "BOLU",
//   "15": "BURDUR",
//   "16": "BURSA",
//   "17": "ÇANAKKALE",
//   "18": "ÇANKIRI",
//   "19": "ÇORUM",
//   "20": "DENİZLİ",
//   "21": "DİYARBAKIR",
//   "22": "EDİRNE",
//   "23": "ELAZIĞ",
//   "24": "ERZİNCAN",
//   "25": "ERZURUM",
//   "26": "ESKİŞEHİR",
//   "27": "GAZİANTEP",
//   "28": "GİRESUN",
//   "29": "GÜMÜŞHANE",
//   "30": "HAKKARİ",
//   "31": "HATAY",
//   "32": "ISPARTA",
//   "33": "MERSİN",
//   "34": "İSTANBUL",
//   "35": "İZMİR",
//   "36": "KARS",
//   "37": "KASTAMONU",
//   "38": "KAYSERİ",
//   "39": "KIRKLARELİ",
//   "40": "KIRŞEHİR",
//   "41": "KOCAELİ",
//   "42": "KONYA",
//   "43": "KÜTAHYA",
//   "44": "MALATYA",
//   "45": "MANİSA",
//   "46": "KAHRAMANMARAŞ",
//   "47": "MARDİN",
//   "48": "MUĞLA",
//   "49": "MUŞ",
//   "50": "NEVŞEHİR",
//   "51": "NİĞDE",
//   "52": "ORDU",
//   "53": "RİZE",
//   "54": "SAKARYA",
//   "55": "SAMSUN",
//   "56": "SİİRT",
//   "57": "SİNOP",
//   "58": "SİVAS",
//   "59": "TEKİRDAĞ",
//   "60": "TOKAT",
//   "61": "TRABZON",
//   "62": "TUNCELİ",
//   "63": "ŞANLIURFA",
//   "64": "UŞAK",
//   "65": "VAN",
//   "66": "YOZGAT",
//   "67": "ZONGULDAK",
//   "68": "AKSARAY",
//   "69": "BAYBURT",
//   "70": "KARAMAN",
//   "71": "KIRIKKALE",
//   "72": "BATMAN",
//   "73": "ŞIRNAK",
//   "74": "BARTIN",
//   "75": "ARDAHAN",
//   "76": "IĞDIR",
//   "77": "YALOVA",
//   "78": "KARABüK",
//   "79": "KİLİS",
//   "80": "OSMANİYE",
//   "81": "DÜZCE"
// }

// let data = []

// let a = ()=> {
//   for (const [key, value] of Object.entries(cities)){
//     data.push({id: key, name: value, countryId: 1})
//   }
// }
// a()
// console.log(data)

module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      "Cities",
      [
        { id: 1, name: "ADANA", countryId: 1 },
        { id: 2, name: "ADIYAMAN", countryId: 1 },
        { id: 3, name: "AFYONKARAHİSAR", countryId: 1 },
        { id: 4, name: "AĞRI", countryId: 1 },
        { id: 5, name: "AMASYA", countryId: 1 },
        { id: 6, name: "ANKARA", countryId: 1 },
        { id: 7, name: "ANTALYA", countryId: 1 },
        { id: 8, name: "ARTVİN", countryId: 1 },
        { id: 9, name: "AYDIN", countryId: 1 },
        { id: 10, name: "BALIKESİR", countryId: 1 },
        { id: 11, name: "BİLECİK", countryId: 1 },
        { id: 12, name: "BİNGÖL", countryId: 1 },
        { id: 13, name: "BİTLİS", countryId: 1 },
        { id: 14, name: "BOLU", countryId: 1 },
        { id: 15, name: "BURDUR", countryId: 1 },
        { id: 16, name: "BURSA", countryId: 1 },
        { id: 17, name: "ÇANAKKALE", countryId: 1 },
        { id: 18, name: "ÇANKIRI", countryId: 1 },
        { id: 19, name: "ÇORUM", countryId: 1 },
        { id: 20, name: "DENİZLİ", countryId: 1 },
        { id: 21, name: "DİYARBAKIR", countryId: 1 },
        { id: 22, name: "EDİRNE", countryId: 1 },
        { id: 23, name: "ELAZIĞ", countryId: 1 },
        { id: 24, name: "ERZİNCAN", countryId: 1 },
        { id: 25, name: "ERZURUM", countryId: 1 },
        { id: 26, name: "ESKİŞEHİR", countryId: 1 },
        { id: 27, name: "GAZİANTEP", countryId: 1 },
        { id: 28, name: "GİRESUN", countryId: 1 },
        { id: 29, name: "GÜMÜŞHANE", countryId: 1 },
        { id: 30, name: "HAKKARİ", countryId: 1 },
        { id: 31, name: "HATAY", countryId: 1 },
        { id: 32, name: "ISPARTA", countryId: 1 },
        { id: 33, name: "MERSİN", countryId: 1 },
        { id: 34, name: "İSTANBUL", countryId: 1 },
        { id: 35, name: "İZMİR", countryId: 1 },
        { id: 36, name: "KARS", countryId: 1 },
        { id: 37, name: "KASTAMONU", countryId: 1 },
        { id: 38, name: "KAYSERİ", countryId: 1 },
        { id: 39, name: "KIRKLARELİ", countryId: 1 },
        { id: 40, name: "KIRŞEHİR", countryId: 1 },
        { id: 41, name: "KOCAELİ", countryId: 1 },
        { id: 42, name: "KONYA", countryId: 1 },
        { id: 43, name: "KÜTAHYA", countryId: 1 },
        { id: 44, name: "MALATYA", countryId: 1 },
        { id: 45, name: "MANİSA", countryId: 1 },
        { id: 46, name: "KAHRAMANMARAŞ", countryId: 1 },
        { id: 47, name: "MARDİN", countryId: 1 },
        { id: 48, name: "MUĞLA", countryId: 1 },
        { id: 49, name: "MUŞ", countryId: 1 },
        { id: 50, name: "NEVŞEHİR", countryId: 1 },
        { id: 51, name: "NİĞDE", countryId: 1 },
        { id: 52, name: "ORDU", countryId: 1 },
        { id: 53, name: "RİZE", countryId: 1 },
        { id: 54, name: "SAKARYA", countryId: 1 },
        { id: 55, name: "SAMSUN", countryId: 1 },
        { id: 56, name: "SİİRT", countryId: 1 },
        { id: 57, name: "SİNOP", countryId: 1 },
        { id: 58, name: "SİVAS", countryId: 1 },
        { id: 59, name: "TEKİRDAĞ", countryId: 1 },
        { id: 60, name: "TOKAT", countryId: 1 },
        { id: 61, name: "TRABZON", countryId: 1 },
        { id: 62, name: "TUNCELİ", countryId: 1 },
        { id: 63, name: "ŞANLIURFA", countryId: 1 },
        { id: 64, name: "UŞAK", countryId: 1 },
        { id: 65, name: "VAN", countryId: 1 },
        { id: 66, name: "YOZGAT", countryId: 1 },
        { id: 67, name: "ZONGULDAK", countryId: 1 },
        { id: 68, name: "AKSARAY", countryId: 1 },
        { id: 69, name: "BAYBURT", countryId: 1 },
        { id: 70, name: "KARAMAN", countryId: 1 },
        { id: 71, name: "KIRIKKALE", countryId: 1 },
        { id: 72, name: "BATMAN", countryId: 1 },
        { id: 73, name: "ŞIRNAK", countryId: 1 },
        { id: 74, name: "BARTIN", countryId: 1 },
        { id: 75, name: "ARDAHAN", countryId: 1 },
        { id: 76, name: "IĞDIR", countryId: 1 },
        { id: 77, name: "YALOVA", countryId: 1 },
        { id: 78, name: "KARABüK", countryId: 1 },
        { id: 79, name: "KİLİS", countryId: 1 },
        { id: 80, name: "OSMANİYE", countryId: 1 },
        { id: 81, name: "DÜZCE", countryId: 1 },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  },
};
