"use strict";
// const cities = {
//   "1": "ADANA",
//   "2": "ADIYAMAN",
//   "3": "AFYONKARAHİSAR",
//   "4": "AĞRI",
//   "5": "AMASYA",
//   "6": "ANKARA",
//   "7": "ANTALYA",
//   "8": "ARTVİN",
//   "9": "AYDIN",
//   "10": "BALIKESİR",
//   "11": "BİLECİK",
//   "12": "BİNGÖL",
//   "13": "BİTLİS",
//   "14": "BOLU",
//   "15": "BURDUR",
//   "16": "BURSA",
//   "17": "ÇANAKKALE",
//   "18": "ÇANKIRI",
//   "19": "ÇORUM",
//   "20": "DENİZLİ",
//   "21": "DİYARBAKIR",
//   "22": "EDİRNE",
//   "23": "ELAZIĞ",
//   "24": "ERZİNCAN",
//   "25": "ERZURUM",
//   "26": "ESKİŞEHİR",
//   "27": "GAZİANTEP",
//   "28": "GİRESUN",
//   "29": "GÜMÜŞHANE",
//   "30": "HAKKARİ",
//   "31": "HATAY",
//   "32": "ISPARTA",
//   "33": "MERSİN",
//   "34": "İSTANBUL",
//   "35": "İZMİR",
//   "36": "KARS",
//   "37": "KASTAMONU",
//   "38": "KAYSERİ",
//   "39": "KIRKLARELİ",
//   "40": "KIRŞEHİR",
//   "41": "KOCAELİ",
//   "42": "KONYA",
//   "43": "KÜTAHYA",
//   "44": "MALATYA",
//   "45": "MANİSA",
//   "46": "KAHRAMANMARAŞ",
//   "47": "MARDİN",
//   "48": "MUĞLA",
//   "49": "MUŞ",
//   "50": "NEVŞEHİR",
//   "51": "NİĞDE",
//   "52": "ORDU",
//   "53": "RİZE",
//   "54": "SAKARYA",
//   "55": "SAMSUN",
//   "56": "SİİRT",
//   "57": "SİNOP",
//   "58": "SİVAS",
//   "59": "TEKİRDAĞ",
//   "60": "TOKAT",
//   "61": "TRABZON",
//   "62": "TUNCELİ",
//   "63": "ŞANLIURFA",
//   "64": "UŞAK",
//   "65": "VAN",
//   "66": "YOZGAT",
//   "67": "ZONGULDAK",
//   "68": "AKSARAY",
//   "69": "BAYBURT",
//   "70": "KARAMAN",
//   "71": "KIRIKKALE",
//   "72": "BATMAN",
//   "73": "ŞIRNAK",
//   "74": "BARTIN",
//   "75": "ARDAHAN",
//   "76": "IĞDIR",
//   "77": "YALOVA",
//   "78": "KARABüK",
//   "79": "KİLİS",
//   "80": "OSMANİYE",
//   "81": "DÜZCE"
// }

// let data = []

// let a = ()=> {
//   for (const [key, value] of Object.entries(cities)){
//     data.push({id: key, name: value, countryCode: 'TRY'})
//   }
// }
// a()
// console.log(data)

module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      "Cities",
      [
        { id: 1, name: "ADANA", countryCode: 'TRY' },
        { id: 2, name: "ADIYAMAN", countryCode: 'TRY' },
        { id: 3, name: "AFYONKARAHİSAR", countryCode: 'TRY' },
        { id: 4, name: "AĞRI", countryCode: 'TRY' },
        { id: 5, name: "AMASYA", countryCode: 'TRY' },
        { id: 6, name: "ANKARA", countryCode: 'TRY' },
        { id: 7, name: "ANTALYA", countryCode: 'TRY' },
        { id: 8, name: "ARTVİN", countryCode: 'TRY' },
        { id: 9, name: "AYDIN", countryCode: 'TRY' },
        { id: 10, name: "BALIKESİR", countryCode: 'TRY' },
        { id: 11, name: "BİLECİK", countryCode: 'TRY' },
        { id: 12, name: "BİNGÖL", countryCode: 'TRY' },
        { id: 13, name: "BİTLİS", countryCode: 'TRY' },
        { id: 14, name: "BOLU", countryCode: 'TRY' },
        { id: 15, name: "BURDUR", countryCode: 'TRY' },
        { id: 16, name: "BURSA", countryCode: 'TRY' },
        { id: 17, name: "ÇANAKKALE", countryCode: 'TRY' },
        { id: 18, name: "ÇANKIRI", countryCode: 'TRY' },
        { id: 19, name: "ÇORUM", countryCode: 'TRY' },
        { id: 20, name: "DENİZLİ", countryCode: 'TRY' },
        { id: 21, name: "DİYARBAKIR", countryCode: 'TRY' },
        { id: 22, name: "EDİRNE", countryCode: 'TRY' },
        { id: 23, name: "ELAZIĞ", countryCode: 'TRY' },
        { id: 24, name: "ERZİNCAN", countryCode: 'TRY' },
        { id: 25, name: "ERZURUM", countryCode: 'TRY' },
        { id: 26, name: "ESKİŞEHİR", countryCode: 'TRY' },
        { id: 27, name: "GAZİANTEP", countryCode: 'TRY' },
        { id: 28, name: "GİRESUN", countryCode: 'TRY' },
        { id: 29, name: "GÜMÜŞHANE", countryCode: 'TRY' },
        { id: 30, name: "HAKKARİ", countryCode: 'TRY' },
        { id: 31, name: "HATAY", countryCode: 'TRY' },
        { id: 32, name: "ISPARTA", countryCode: 'TRY' },
        { id: 33, name: "MERSİN", countryCode: 'TRY' },
        { id: 34, name: "İSTANBUL", countryCode: 'TRY' },
        { id: 35, name: "İZMİR", countryCode: 'TRY' },
        { id: 36, name: "KARS", countryCode: 'TRY' },
        { id: 37, name: "KASTAMONU", countryCode: 'TRY' },
        { id: 38, name: "KAYSERİ", countryCode: 'TRY' },
        { id: 39, name: "KIRKLARELİ", countryCode: 'TRY' },
        { id: 40, name: "KIRŞEHİR", countryCode: 'TRY' },
        { id: 41, name: "KOCAELİ", countryCode: 'TRY' },
        { id: 42, name: "KONYA", countryCode: 'TRY' },
        { id: 43, name: "KÜTAHYA", countryCode: 'TRY' },
        { id: 44, name: "MALATYA", countryCode: 'TRY' },
        { id: 45, name: "MANİSA", countryCode: 'TRY' },
        { id: 46, name: "KAHRAMANMARAŞ", countryCode: 'TRY' },
        { id: 47, name: "MARDİN", countryCode: 'TRY' },
        { id: 48, name: "MUĞLA", countryCode: 'TRY' },
        { id: 49, name: "MUŞ", countryCode: 'TRY' },
        { id: 50, name: "NEVŞEHİR", countryCode: 'TRY' },
        { id: 51, name: "NİĞDE", countryCode: 'TRY' },
        { id: 52, name: "ORDU", countryCode: 'TRY' },
        { id: 53, name: "RİZE", countryCode: 'TRY' },
        { id: 54, name: "SAKARYA", countryCode: 'TRY' },
        { id: 55, name: "SAMSUN", countryCode: 'TRY' },
        { id: 56, name: "SİİRT", countryCode: 'TRY' },
        { id: 57, name: "SİNOP", countryCode: 'TRY' },
        { id: 58, name: "SİVAS", countryCode: 'TRY' },
        { id: 59, name: "TEKİRDAĞ", countryCode: 'TRY' },
        { id: 60, name: "TOKAT", countryCode: 'TRY' },
        { id: 61, name: "TRABZON", countryCode: 'TRY' },
        { id: 62, name: "TUNCELİ", countryCode: 'TRY' },
        { id: 63, name: "ŞANLIURFA", countryCode: 'TRY' },
        { id: 64, name: "UŞAK", countryCode: 'TRY' },
        { id: 65, name: "VAN", countryCode: 'TRY' },
        { id: 66, name: "YOZGAT", countryCode: 'TRY' },
        { id: 67, name: "ZONGULDAK", countryCode: 'TRY' },
        { id: 68, name: "AKSARAY", countryCode: 'TRY' },
        { id: 69, name: "BAYBURT", countryCode: 'TRY' },
        { id: 70, name: "KARAMAN", countryCode: 'TRY' },
        { id: 71, name: "KIRIKKALE", countryCode: 'TRY' },
        { id: 72, name: "BATMAN", countryCode: 'TRY' },
        { id: 73, name: "ŞIRNAK", countryCode: 'TRY' },
        { id: 74, name: "BARTIN", countryCode: 'TRY' },
        { id: 75, name: "ARDAHAN", countryCode: 'TRY' },
        { id: 76, name: "IĞDIR", countryCode: 'TRY' },
        { id: 77, name: "YALOVA", countryCode: 'TRY' },
        { id: 78, name: "KARABüK", countryCode: 'TRY' },
        { id: 79, name: "KİLİS", countryCode: 'TRY' },
        { id: 80, name: "OSMANİYE", countryCode: 'TRY' },
        { id: 81, name: "DÜZCE", countryCode: 'TRY' },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  },
};
